# yaml表示以上对象
person:
  userName: "zhang \n san"
  # 不加引号： json: "userName":"zhang \\n san"， 控制台： zhang \n san
  # 加单引号： json: "userName":"zhang \\n san"， 控制台： zhang \n san
  # 加双引号： json: "userName":"zhang \n san"， 控制台： zhang *换行* san
  # 即： 双引号不会转义（执行\n）， 单引号会转义（不执行\n，把\n变成\\n）
  boss: false
  birth: 2019/12/12 20:12:33
  age: 18
  interests: [篮球,游泳]
  animal:
    - jerry
    - tom
  score:
    english:
      first: 30
      second: 40
      third: 50
    math: [131,140,148]
    chinese: {first: 128,second: 136}
  salarys: [3999,4999.98,5999.99]
  pet:
    name: tomcat
    weight: 23.4
  allPets:
    sick:
      - {name: tom}
      - {name: jerry,weight: 47}
    health: [{name: mario,weight: 47}]